spring.application.name=bichontravel

server.port=${PORT:8080}

# SQLite
spring.datasource.url=jdbc:sqlite:/app/data/bichontravel.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

spring.main.allow-bean-definition-overriding=false